# Generated by Django 4.0.6 on 2023-04-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hero_image',
        ),
    ]
